/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.project.gudang.gui;

/**
 *
 * @author bagas
 */
public class HomeFrame extends javax.swing.JFrame {

    /**
     * Creates new form HomeFrame
     */
    public HomeFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        stockBarangLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        labelUser = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        userStatusLabel = new javax.swing.JLabel();
        stockBarangButton = new javax.swing.JButton();
        barangMasukButton = new javax.swing.JButton();
        barangKeluarButton = new javax.swing.JButton();
        keluarButton = new javax.swing.JButton();
        userManajemenButton = new javax.swing.JButton();
        stockBarangLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        labelUser1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        userStatusLabel1 = new javax.swing.JLabel();
        stockBarangButton1 = new javax.swing.JButton();
        barangMasukButton1 = new javax.swing.JButton();
        barangKeluarButton1 = new javax.swing.JButton();
        keluarButton1 = new javax.swing.JButton();
        userManajemenButton1 = new javax.swing.JButton();

        stockBarangLabel.setText("jLabel4");

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("GUDANG");

        jLabel2.setText("user :");

        labelUser.setText("admin");

        jLabel3.setText("status :");

        userStatusLabel.setText("jLabel4");

        stockBarangButton.setText("Stok Barang");
        stockBarangButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stockBarangButtonActionPerformed(evt);
            }
        });

        barangMasukButton.setText("Barang Masuk");
        barangMasukButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barangMasukButtonActionPerformed(evt);
            }
        });

        barangKeluarButton.setText("Barang Keluar");

        keluarButton.setText("Keluar");

        userManajemenButton.setText("Manajemen User");
        userManajemenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userManajemenButtonActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        stockBarangLabel1.setText("jLabel4");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("GUDANG");

        jLabel5.setText("user :");

        labelUser1.setText("admin");

        jLabel6.setText("status :");

        userStatusLabel1.setText("jLabel4");

        stockBarangButton1.setText("Stok Barang");
        stockBarangButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stockBarangButton1ActionPerformed(evt);
            }
        });

        barangMasukButton1.setText("Barang Masuk");
        barangMasukButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barangMasukButton1ActionPerformed(evt);
            }
        });

        barangKeluarButton1.setText("Barang Keluar");

        keluarButton1.setText("Keluar");

        userManajemenButton1.setText("Manajemen User");
        userManajemenButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userManajemenButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(310, 310, 310)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(135, 135, 135)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel5)
                                .addComponent(jLabel6))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(labelUser1)
                                .addComponent(userStatusLabel1)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(44, 44, 44)
                            .addComponent(stockBarangButton1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(userManajemenButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(barangMasukButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(153, 153, 153)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(barangKeluarButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(keluarButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(stockBarangLabel1)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(labelUser1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(userStatusLabel1)))
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stockBarangButton1)
                    .addComponent(barangMasukButton1)
                    .addComponent(barangKeluarButton1))
                .addGap(18, 18, 18)
                .addComponent(stockBarangLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(keluarButton1)
                    .addComponent(userManajemenButton1))
                .addGap(169, 169, 169))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void stockBarangButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stockBarangButtonActionPerformed
        // TODO add your handling code here:
        HomeFrame hf = new HomeFrame();
        StockBarang sb = new StockBarang();
        this.setVisible(false);
        sb.setVisible(true);
    }//GEN-LAST:event_stockBarangButtonActionPerformed

    private void barangMasukButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barangMasukButtonActionPerformed
        // TODO add your handling code here:
        HomeFrame hf = new HomeFrame();
        StockBarang sb = new StockBarang();
        this.setVisible(false);
        sb.setVisible(true);
    }//GEN-LAST:event_barangMasukButtonActionPerformed

    private void userManajemenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userManajemenButtonActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_userManajemenButtonActionPerformed

    private void stockBarangButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stockBarangButton1ActionPerformed
        // TODO add your handling code here:
        HomeFrame hf = new HomeFrame();
        StockBarang sb = new StockBarang();
        this.setVisible(false);
        sb.setVisible(true);
    }//GEN-LAST:event_stockBarangButton1ActionPerformed

    private void barangMasukButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barangMasukButton1ActionPerformed
        // TODO add your handling code here:
        HomeFrame hf = new HomeFrame();
        StockBarang sb = new StockBarang();
        this.setVisible(false);
        sb.setVisible(true);
    }//GEN-LAST:event_barangMasukButton1ActionPerformed

    private void userManajemenButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userManajemenButton1ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_userManajemenButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton barangKeluarButton;
    private javax.swing.JButton barangKeluarButton1;
    private javax.swing.JButton barangMasukButton;
    private javax.swing.JButton barangMasukButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton keluarButton;
    private javax.swing.JButton keluarButton1;
    private javax.swing.JLabel labelUser;
    private javax.swing.JLabel labelUser1;
    private javax.swing.JButton stockBarangButton;
    private javax.swing.JButton stockBarangButton1;
    private javax.swing.JLabel stockBarangLabel;
    private javax.swing.JLabel stockBarangLabel1;
    private javax.swing.JButton userManajemenButton;
    private javax.swing.JButton userManajemenButton1;
    private javax.swing.JLabel userStatusLabel;
    private javax.swing.JLabel userStatusLabel1;
    // End of variables declaration//GEN-END:variables
}
